services:
  - type: web
    name: zerodha-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URL
        sync: false
